- hosts: jenkins
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all apt packages
      apt:
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull the Jenkins Docker image
      docker_image:
        name: jenkins/jenkins:lts
        tag: latest
        source: pull

    - name: Run Jenkins container with specific name, port, and in the background
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"  # Expose Jenkins on port 8080
          - "50000:50000"  # Expose Jenkins agent port
        detach: yes  # Run the container in the background
        volumes:
          - jenkins_home:/var/jenkins_home

    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 60

    - name: Print the initial admin password
      command: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_admin_password

    - name: Display the initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_admin_password.stdout }}"
